model:
  name: GradientBoostingRegressor
  parameters:
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 150
    random_state: 42
    subsample: 1.0
  description: Modelo de regresión basado en boosting para la estimación de valores de propiedades.

data:
  train_test_split:
    test_size: 0.2
    random_state: 42

evaluation:
  metrics:
    - MAE
    - RMSE
    - R2
